spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.48.0.191:3306/recorder-cn-tewst?autoReconnect=true&useUnicode=true&charset=utf8mb4
    username: recorder-cn
    password: recorder-cn-123
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  redis:
    cluster:
      nodes: 10.29.10.14:8700

  elasticsearch:
    rest:
      uris: internal-ad86a960929a041d1bc2f548a26ee1b5-2043565051.us-west-2.elb.amazonaws.com:9200
      username: elastic
      password: elastic

#  elasticsearch:
#    rest:
#      uris: http://10.121.2.137:9200,http://10.121.2.153:9200,http://10.121.2.49:9200
#      username: elastic
#      password: doglobal

server:
  http2:
    enabled: true
